### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by Tr2e** [AgoraIO-Community/visionOS-Quickstart#1]
![image](https://github.com/AgoraIO-Community/visionOS-Quickstart/assets/17601182/85e27b02-40e7-4310-bb94-399c95851eeb)

An error occurred when I run this demo; I don't know why

**Comment by icywind** [comment]
Did you get the SDK installed? 
BTW, we just updated the code and the SDK dependency. Please try again.  It should work straight out of the box, after you added your App ID in the code.
